config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "/sign-up", to: "registration#new"
  post "/sign-up", to: "registration#create"

  get "/login", to: "session#new"
  post "/login", to: "session#create"
  delete "/logout", to: "session#destroy"

  resources :users
  get "/profile", to: "users#index"

  get "/password", to: "password#edit", as: "edit_password"
  patch "/password", to: "password#update", as: "update_password"

  get "password/reset", to: "password_resets#new", as: :password_reset
  post "password/reset", to: "password_resets#create", as: :password_reset_create
  get "password/reset/edit", to: "password_resets#edit", as: :password_reset_edit
  patch "password/reset/edit", to: "password_resets#update", as: :password_reset_update

  get "/auth/twitter/callback", to: "omniauth_callbacks#twitter"
  get "/auth/github/callback", to: "omniauth_callbacks#github"

  resources :twitter_accounts
  resources :tweets
  resources :github
  resources :github_accounts
  
  # Defines the root path route ("/")
  root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/github_account.rb
class GithubAccount < ApplicationRecord
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: { minimum: 1, maximum: 280 }

  validates :published_at, presence: true

  after_initialize do
    self.published_at ||= 24.hours.from_now
  end

  after_save_commit do
    TweetJob.set(wait_until: published_at).perform_later(self) if published_at_previously_changed?
  end

  def published?
    tweet_id?
  end

  def publish_to_twitter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user
  has_many :tweets, dependent: :destroy
  validates :username, uniqueness: true

  def client
    Twitter::REST::Client.new do |config|
      config.consumer_key = Rails.application.credentials.dig(:twitter, :api_key)
      config.consumer_secret = Rails.application.credentials.dig(:twitter, :api_secret)
      config.access_token = token
      config.access_token_secret = secret
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :twitter_accounts
  has_many :github_accounts
  has_many :tweets

  has_secure_password

  validates :email, presence: true,
                    format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'email must be a valid email address' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    return unless session[:user_id]

    Current.user = User.find_by(id: session[:user_id])
  end

  def user_is_logged_in?
    Current.user.nil?
  end

  def require_login!
    redirect_to login_path, alert: 'Authentication Required' if user_is_logged_in?
  end
end

app/controllers/github_controller.rb
class GithubController < ApplicationController
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index; end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  before_action :require_login!

  def edit; end

  def update
    user = Current.user.update(update_params)
    if user
      redirect_to profile_path, notice: 'Password changed successfully'
    else
      render :edit
    end
  end

  private

  def update_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully'
    else
      flash[:alert] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out'
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_login!
  before_action :set_tweet, only: %i[edit update destroy]

  def index
    @tweets = Current.user.tweets
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Current.user.tweets.new(tweet_params)

    if @tweet.save
      redirect_to tweets_path, notice: 'Tweet Scheduled successfully'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: 'Scheduled tweet updated successfully'
    else
      render :edit
    end
  end

  def destroy
    if @tweet.destroy
      redirect_to tweets_path, notice: 'Tweet unscheduled successfully'
    else
      redirect_to request.referrer
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:twitter_account_id, :body, :published_at)
  end

  def set_tweet
    @tweet = Current.user.tweets.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/github_accounts_helper.rb
module GithubAccountsHelper
end

app/helpers/github_helper.rb
module GithubHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/twitter_accounts_helper.rb
module TwitterAccountsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tweets/_form.html.erb
<div class="form">
    <%= form_with model: tweet do |form| %>
        <div class="mb-3">
            <%= form.label :twitter_account %>
            <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, {class: "form-control"} %>
            <%= link_to "Connect a Twitter Account", "/auth/twitter", method: :post, class: " mt-2 bg-gradient", data: {turbo: "false"} %>
        </div>

        <div class="mb-3">
            <%= form.label :body %>
            <%= form.text_area :body, class: "form-control" %>
        </div>

        <div class="mb-3">
            <%= form.label :publish_at %>
            <div class="form-control">
                <%= form.datetime_select :published_at, class: "" %>
            </div>
        </div>

        <%= form.submit "Schedule Tweet", class: "btn btn-primary bg-gradient" %>
    <% end %>
</div>

app/views/tweets/_tweet.html.erb
<div class="col-md-6">
    <div class="card">
        <div class="card-body">
            <p><%= tweet.body %></p>
            <div class="d-flex align-items-center gap-2">
                <%= image_tag(tweet.twitter_account.image, class: "account-img rounded-circle", alt: tweet.twitter_account.name) %>
                <div>
                    <h6 class="account-name"><%= tweet.twitter_account.name %></h6>
                    <%= link_to "@#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}" %>
                </div>
            </div>
        </div>
        <div class="d-flex p-3 align-items-center justify-content-between">
            <% if tweet.published? %>
                <%= link_to "View tweet", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}" , class: "btn btn-sm btn-info btn-gradient" %>
            <% else %>
                <p>Scheduled for: <%= l tweet.published_at, format: :short %></p>
                <div>
                <%= link_to "Edit", edit_tweet_path(tweet.id), class: "btn  btn-sm btn-outline-primary btn-gradient" %>
                <%= link_to "Delete", tweet ,  class: "btn  btn-sm btn-outline-danger btn-gradient", data: { turbo_method: :delete,
                turbo_confirm: "Are you sure you want to delete this scheduled tweet?" } %>
                </div>
            <% end %>
            
        </div>
    </div>
</div>

app/views/tweets/edit.html.erb
<h2 class="my-3">Edit Scheduled tweet</h2>

<%= render 'tweets/form', tweet: @tweet %>

app/views/tweets/index.html.erb
<div class="d-flex justify-content-between">
    <h2>Tweets</h2>
    <% if Current.user.twitter_accounts.any? %>
        <%= link_to "Schedule a Tweet", new_tweet_path, class: "btn btn-primary rounded bg-gradient" %>
    <% end %>
</div>

<% if Current.user.twitter_accounts.none? %>
    <%= button_to "Connect a Twitter Account", "/auth/twitter", method: :post, class: "btn btn-primary rounded bg-gradient", data: {turbo: "false"} %>
<% end %>

<%= render @tweets %>

app/views/tweets/new.html.erb
<div class="form">
    <%= render 'tweets/form', tweet: @tweet %>
</div>

app/views/users/index.html.erb
<h1><%= Current.user.email %> Profile<h2>

<%= link_to "Update Password", edit_password_path, class: "btn btn-primary" %>