config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "/sign-up", to: "registration#new"
  post "/sign-up", to: "registration#create"

  get "/login", to: "session#new"
  post "/login", to: "session#create"
  delete "/logout", to: "session#destroy"

  resources :users
  get "/profile", to: "users#index"

  get "/password", to: "password#edit", as: "edit_password"
  patch "/password", to: "password#update", as: "update_password"

  get "password/reset", to: "password_resets#new", as: :password_reset
  post "password/reset", to: "password_resets#create", as: :password_reset_create
  get "password/reset/edit", to: "password_resets#edit", as: :password_reset_edit
  patch "password/reset/edit", to: "password_resets#update", as: :password_reset_update

  get "/auth/twitter/callback", to: "omniauth_callbacks#twitter"
  get "/auth/github/callback", to: "omniauth_callbacks#github"

  resources :twitter_accounts
  resources :tweets
  resources :github
  resources :github_accounts
  
  # Defines the root path route ("/")
  root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/github_account.rb
class GithubAccount < ApplicationRecord
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: { minimum: 1, maximum: 280 }

  validates :published_at, presence: true

  after_initialize do
    self.published_at ||= 24.hours.from_now
  end

  after_save_commit do
    TweetJob.set(wait_until: published_at).perform_later(self) if published_at_previously_changed?
  end

  def published?
    tweet_id?
  end

  def publish_to_twitter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user
  has_many :tweets, dependent: :destroy
  validates :username, uniqueness: true

  def client
    Twitter::REST::Client.new do |config|
      config.consumer_key = Rails.application.credentials.dig(:twitter, :api_key)
      config.consumer_secret = Rails.application.credentials.dig(:twitter, :api_secret)
      config.access_token = token
      config.access_token_secret = secret
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :twitter_accounts
  has_many :github_accounts
  has_many :tweets

  has_secure_password

  validates :email, presence: true,
                    format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'email must be a valid email address' }
end

app/controllers/github_controller.rb
class GithubController < ApplicationController
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index; end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully'
    else
      flash[:alert] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out'
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_login!
  before_action :set_tweet, only: %i[edit update destroy]

  def index
    @tweets = Current.user.tweets
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Current.user.tweets.new(tweet_params)

    if @tweet.save
      redirect_to tweets_path, notice: 'Tweet Scheduled successfully'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: 'Scheduled tweet updated successfully'
    else
      render :edit
    end
  end

  def destroy
    if @tweet.destroy
      redirect_to tweets_path, notice: 'Tweet unscheduled successfully'
    else
      redirect_to request.referrer
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:twitter_account_id, :body, :published_at)
  end

  def set_tweet
    @tweet = Current.user.tweets.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/github_accounts_helper.rb
module GithubAccountsHelper
end

app/helpers/github_helper.rb
module GithubHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="main">
        <div class="gradient"></div>
    </div>
    
    <div class="app">
      <%= render partial: "shared/navbar" %>
      <main>
        <div class="container">
          <%= render partial: "shared/flash" %>
          <%= yield %>
        </div>
      </main>
    </div>
  </body>
</html>

app/views/shared/_account_card.html.erb
<div class="col-md-3">
    <div class="card">
        <div class="card-body d-flex align-items-center justify-content-between">
            <%= image_tag(account.image, class: "account-img rounded-circle", alt: account.name) %>
            <div>
                <h5 class="account-name"><%= account.name %></h5>
                <%= link_to "@#{account.username}", "https://twitter.com/#{account.username}" %>
            </div>
        </div>
        <%= button_to "Disconnect", account , method: :delete, class: "btn mt-0 m-3 btn-sm btn-danger btn-gradient" %>
    </div>
</div>

app/views/shared/_flash.html.erb
<% if flash[:alert] %>
    <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

<% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <a class="navbar-brand me-5 border p-2 text-primary bg-light rounded-circle" href="#">Gitweet</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to "Twitter Accounts", twitter_accounts_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "GitHub Accounts", github_accounts_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Tweets", tweets_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto mb2 mb-lg-0">
      <% if Current.user %>
          <li class="nav-item">
            <%= link_to Current.user.email, profile_path,  class: "nav-link" %>
          </li>
          
          <li class="nav-item">
            <%= button_to "Logout", logout_path, class: "btn btn-light", method: :delete %>
          </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign In", login_path,  class: "nav-link" %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>